### ISSUE TITLE
The type or namespace name 'Icons' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by codemaker** [oliverscheer/blazor-fluent-ui-demo#3]
Hi

I am getting below error while building.  

The type or namespace name 'Icons' could not be found (are you missing a using directive or an assembly reference?)

Note: Nuget package is up to date.

**Comment by oliverscheer** [comment]
Thank you for your feedback. The solution was outdated, I updated it to .net and updated also the nuget packages. It should run now.
